theme: jekyll-theme-minimal
title: Mithros Privacy Policy
description: Privacy Policy for the Mithros app which provides net-streaks check-ins and response plans for individuals recovering from pornography addiction. 